/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";

/* USERS */
export const GET_USERS = "GET_USERS";
export const DELETE_USERS = "DELETE_USERS";
export const EDIT_USERS = "EDIT_USERS";
export const ENABLE_USERS = "ENABLE_USERS";
export const GET_ROLES = "GET_ROLES";
export const SET_USER_ROLE = "SET_USER_ROLE";
export const SET_USERS_DATA = "SET_USERS_DATA";
export const ERROR_USERS_DATA = "ERROR_USERS_DATA";
export const CHANGE_FILTER_USERS = "CHANGE_FILTER_USERS";
export const EDIT_USER_ON_MODAL = "EDIT_USER_ON_MODAL";
export const POST_USER = "POST_USER";

export const GET_USER_PERMISSIONS = "GET_USER_PERMISSIONS";
export const SET_USER_PERMISSIONS = "SET_USER_PERMISSIONS";

/* TEAMS */
export const GET_TEAMS = "GET_TEAMS";
export const SET_TEAMS = "SET_TEAMS";
export const ERROR_GETTING_TEAMS = "ERROR_GETTING_TEAMS";
export const DELETE_TEAM = "DELETE_TEAM";
export const EDIT_TEAM = "EDIT_TEAM";
export const EDIT_TEAM_ON_MODAL = "EDIT_TEAM_ON_MODAL";
export const POST_TEAM = "POST_TEAM";

/* RESTRICTIONS */
export const GET_RESTRICTIONS = "GET_RESTRICTIONS";
export const SET_RESTRICTIONS = "SET_RESTRICTIONS";
export const ERROR_GETTING_RESTRICTIONS = "ERROR_GETTING_RESTRICTIONS";
export const DELETE_RESTRICTION = "DELETE_RESTRICTION";
export const POST_RESTRICTION = "POST_RESTRICTION";

/* PROJETS */
export const GET_PROJETS = "GET_PROJETS";
export const SET_PROJETS = "SET_PROJETS";
export const ERROR_GETTING_PROJETS = "ERROR_GETTING_PROJETS";
export const DELETE_PROJET = "DELETE_PROJET";
export const POST_PROJET = "POST_PROJET";

/* BOXS */
export const GET_BOXS = "GET_BOXS";
export const SET_BOXS = "SET_BOXS";
export const ERROR_GETTING_BOXS = "ERROR_GETTING_BOXS";
export const GET_BOX_METADATA = "GET_BOX_METADATA";
export const SET_BOX_METADATA = "SET_BOX_METADATA";
export const ERROR_GETTING_BOX_META = "ERROR_GETTING_BOX_META";
export const UPDATE_BOX_METADATA = "UPDATE_BOX_METADATA";
export const GET_BOX_DOCS = "GET_BOX_DOCS";
export const SET_BOX_DOCS = "SET_BOX_DOCS";
export const ERROR_GETTING_BOX_DOCS = "ERROR_GETTING_BOX_DOCS";

/* DOCS */
export const GET_DOCS_PAGES = "GET_DOCS_PAGES";
export const SET_DOCS_PAGES = "SET_DOCS_PAGES";
export const ERROR_GETTING_DOCS_PAGES = "ERROR_GETTING_DOCS_PAGES";

export const GET_DOCS_METADATA = "GET_DOCS_METADATA";
export const SET_DOCS_METADATA = "SET_DOCS_METADATA";
export const ERROR_GETTING_DOCS_META = "ERROR_GETTING_DOCS_META";

export const UPDATE_DOCS_METADATA = "UPDATE_DOCS_METADATA";

export const MISSINGS_PAGES = "MISSINGS_PAGES";
export const SET_MISSINGS_PAGES = "SET_MISSINGS_PAGES";
export const ERROR_MISSINGS_PAGES = "ERROR_MISSINGS_PAGES";

/* Pages */
export const GET_PAGE_METADATA = "GET_PAGE_METADATA";
export const SET_PAGE_METADATA = "SET_PAGE_METADATA";
export const ERROR_GETTING_PAGE_META = "ERROR_GETTING_PAGE_META";
export const UPDATE_PAGE_METADATA = "UPDATE_PAGE_METADATA";
export const DOWNLOAD_PAGE = "DOWNLOAD_PAGE";
export const UPLOAD_PAGE = "UPLOAD_PAGE";

export const SEARCH_PAGE = "SEARCH_PAGE";
export const SET_SEARCH_PAGE = "SET_SEARCH_PAGE";
export const ERROR_GETTING_SEARCH_PAGE = "ERROR_GETTING_SEARCH_PAGE";

export const AUDIT_SEARCH = "AUDIT_SEARCH";
export const SET_AUDIT_SEARCH = "SET_AUDIT_SEARCH";
export const ERROR_AUDIT_SEARCH = "ERROR_AUDIT_SEARCH";

/** Metadata */
export const BOX_WITHOUT_META = "BOX_WITHOUT_META";
export const DOC_WITHOUT_META = "DOC_WITHOUT_META";
export const PAGE_WITHOUT_META = "PAGE_WITHOUT_META";
